name: deployment

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  linting_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: output-debug
        run: echo "ok"

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: test
        run: npm run test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: playwright-report/
          retention-days: 1

  tag_release:
    needs: [linting_and_build]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  production_deployment:

      needs: [tag_release]
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: deploy to production
          run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
